flowchart LR
  subgraph f0["api.ts"]
    n965d6db927["constructor()"]
    n71584cfab9["status()"]
  end
  subgraph f1["protocol.ts"]
    n53ecf45228["isRobotStatus()"]
  end
  classDef alto fill:#5b1f2a,stroke:#ff7a7a,color:#fff
  classDef medio fill:#4a3717,stroke:#ffca67,color:#fff
  classDef bajo fill:#123b3a,stroke:#39e6aa,color:#fff
  class n965d6db927 bajo
  class n71584cfab9 bajo
  class n53ecf45228 bajo
